version: '3'

services:

  haproxy1:
    image: stevecliff/haproxy:001
    container_name: haproxy1
    ports:
      - '80:80'
      - '8404:8404'
      - '5555:5555'
    volumes:
      - ${PWD}/config:/usr/local/etc/haproxy
    networks:
      - dev
      - prod
      - default

networks:
  default:
  prod:
    external:
      name: customer_prod
  dev:
    external:
      name: customer_dev
