#!/bin/bash

curl -X POST "http://admin:poctest@localhost:5555/v2/services/haproxy/configuration/raw?skip_version=true&force_reload=true" \
-H "Content-Type: text/plain" \
--upload-file $1

#docker exec -it oxpilot curl -X POST 'http://admin:poctest@haproxy:5555/v2/services/haproxy/configuration/raw?skip_version=true&force_reload=true' -H 'Content-Type: text/plain' --upload-file /usr/local/etc/haproxy/haproxy.cfg
