#!/bin/bash

CFGDIR="/data/haproxy1"

# Stop (just in case)
docker kill haproxy1 # fast!
docker-compose down

# Init config (to ensure API running ready)
rm ${CFGDIR} -rf
mkdir -p ${CFGDIR}
cp haproxy.cfg.init ${CFGDIR}/haproxy.cfg

# Start up containers
docker-compose up -d
