version: "3"

services:

  vault:
    image: vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - /docker/vault/config:/vault/config
      - /docker/vault/file:/vault/file
      - /docker/vault/logs:/vault/logs
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.hcl
