version: '3'

services:

  prod1:
    image: containous/whoami
    container_name: prod1
    hostname: prod1
    networks:
      - prod

  prod2:
    image: containous/whoami
    container_name: prod2
    hostname: prod2
    networks:
      - prod

  dev1:
    image: containous/whoami
    container_name: dev1
    hostname: dev1
    networks:
      - dev

  dev2:
    image: containous/whoami
    container_name: dev2
    hostname: dev2
    networks:
      - dev

networks:
  prod:
    external:
      name: customer_prod
  dev:
    external:
      name: customer_dev
