#!/bin//bash

## Get the current version
VERSION=`curl -s -X GET --user admin:poctest \
"http://localhost:5555/v2/services/haproxy/configuration/frontends" | jq ._version`
echo "Current Version is: $VERSION"

## Create a new Transaction ID
echo "Creating a new Transaction ID..."
T_ID=`curl -s -X POST --user admin:poctest \
-H "Content-Type: application/json" \
http://localhost:5555/v2/services/haproxy/transactions?version="${VERSION}" | jq '.id'| tr -d '"'`

## Do something
curl -s -X POST --user admin:poctest \
  -H "Content-Type: application/json" \
  -d '{"name": "test_frontend", "default_backend": "dev", "mode": "http", "maxconn": 2000}' \
  http://localhost:5555/v2/services/haproxy/configuration/frontends?version=${VERSION}

## Submit transaction
echo "Submitting Transaction"
curl -X PUT --user admin:poctest \
-H "Content-Type: application/json" \
"http://localhost:5555/v2/services/haproxy/transactions/$T_ID"

echo "Done."
